### ISSUE TITLE
Some Dojo events like inputbox keydown aren't fired when QuestionMark.js is loaded

### ISSUE THREAD

**Issue by dereckson** [impressivewebs/QuestionMark.js#6]
When QuestionMark is loaded, some events seem to be intercepted without being further processed to other scripts.

HTML relevant code:

```
<input type="text" id="entry">

<script src="/js/question.mark.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/dojo/1.9.2/dojo/dojo.js"></script>
```

JavaScript Dojo-based code:

```
require(["dojo/query"], function (query) {
    query("#entry").on("keydown", function (e) {
        console.log("Event: ", e);
    });
});
```

**Comment by impressivewebs** [comment]
Not sure if this was still a problem but I've overhauled the code and Dojo isn't used much these days so I would assume this is safe to just close.
