### ISSUE TITLE
Make AJAX URL an option and also make AJAX optional!

### ISSUE THREAD

**Issue by jasondavis** [impressivewebs/QuestionMark.js#8]
Very cool, I was actually bout to build this same thing for my project as I wanted something like StackOverflow has in my Project Management app.

By luck, I found this project tonight!

Just an idea for a feature/option....

Instead of requiring an AJAX request to server, would be nice to make it another option to include the keyboard HTML inside of a template DIV on the page and then this script would read from that template.

So it could use the current AJAX method, however if someone wanted to they could instead put the HTML in the DOM for the keyboard content.

Another nice option for people who do use the AJAX for content would be to allow them to set the URL.

I mention this because in SugarCRM where I am working now, I cannot set a URL like this script requires....I have to modify the URL in the script since it is hard-coded there.

Just ideas, thanks for sharing

**Comment by wouters-frederik** [comment]
I have forked this project and added this capability:
https://github.com/wouters-frederik/QuestionMark.js/blob/master/README.md

**Comment by impressivewebs** [comment]
Thanks for this. I'll close this issue because I didn't plan to implement this anyhow.
